img = imread('G:\input\00274.jpg');  


param.lambda = 2000;
param.sigma_start = 15.0;
param.sigma_end = 0.5;
%nks:
%param = struct(...
%    'lambda', 3000.0, ...
%    'sigma_start', 12.0, ...
%    'sigma_end', 0.25, ...
%    'p_min', 0.8, ...
%    'itr_num', 50, ...
%    'mu', 1.15, ...
%    'rho', 1.15, ...
%    'lambda2', 0 ...
%);
%sps:
%param = struct(...
%    'lambda', 4000.0, ...
%    'sigma_start', 25.0, ...
%    'sigma_end', 1.0, ...
%    'p_min', 0.8, ...
%    'itr_num', 15, ...
%    'mu', 1.15, ...
%    'rho', 8.0, ...
%    'lambda2', 0 ...
%);
% 调用平滑函数
res = welsch_smoothing(img, param);

% 显示结果
figure;
subplot(1,2,1); imshow(img); title('原图');
subplot(1,2,2); imshow(res); title('Welsch 平滑结果');
